### ISSUE TITLE
Add support for juju-*-proxy variables

### ISSUE THREAD

**Issue by aieri** [juju/charm-helpers#304]
When adding PPA sources behind a proxy, add-apt-repository and apt-key commands are invoked.
Since those commands don't really honor apt proxy variables (see LP#1433761), the source addition will hang if the model is configured to use the charm specific juju-*-proxy variables instead of the legacy http/https proxy variables.
I believe the juju-*-proxy variables should be used to populate the environment of the subshells where add-apt-repository and apt-key will be run.

**Comment by dshcherb** [comment]
@aieri 

This is already done in charm-helpers for bionic+ and partially for earlier versions (key handling only). Pre-bionic releases of the software-properties package do not handle proxy variables passed to it so add-apt-repository will not properly resolve ppa shortcuts.

See https://github.com/juju/charm-helpers/pull/248

The code merged there
- uses curl & https instead of apt-key (deprecated) which works for any version of Ubuntu;
- passes the new proxy settings to add-apt-repository;
- provides a helper for charms to use new proxy settings (usage example: https://github.com/Juniper/contrail-charms/pull/49/commits/cc957687b055d707a253b2f51a50027cf7bc96a9).

For Xenial, the workaround for the lack of proxy handling by software-properties package is using full deb-style source lines instead of ppa shortcuts:

```deb [arch=<arches-csv] uri distribution [component1] [component2] [...]```

Using full keys and sources makes add-apt-repository completely offline (combinations are possible as well).

The helper code needs to be used by charm authors according to the behavior of the charm as not every http(s) access is meant to be going through a proxy server. Subjectively, a lot of traffic will be east-west and will not need to cross security boundaries set by proxy servers (either traffic within the same fabric or routed in the organization). Traffic that needs to pass proxy servers will typically be related to package installation hence usage of the helper has to be explicit (which means no issues with no-proxy & CIDR support).

As of today, the only action is to rebuild the existing charms which rely on standard fetch.add_source function. If they have any curl or wget calls to external resources or have software they need to configure to use proxies (such as Docker) they have to use the env_proxy_settings helper similar to this example https://github.com/Juniper/contrail-charms/pull/49/commits/cc957687b055d707a253b2f51a50027cf7bc96a9

juju-no-proxy only needs to contain cloud provider addresses or hostnames where appropriate (controller IPs are auto-added by Juju), otherwise this traffic will be sent through a proxy.

Charms that depend on snaps can now use snap-https-proxy model-configs and do not have to provide special charm configs for that.

**Comment by aieri** [comment]
Thanks for clarifying @dshcherb, specifying PPAs and GPG keys explicitly is a viable workaround for the Xenial clouds. I think this issue can be closed.
