### ISSUE TITLE
Latest certifi (2022.5.18 to 2022.6.15) breaks on Xenial

### ISSUE THREAD

**Issue by hloeung** [juju/charm-helpers#721]
Hi,

The latest pytohn certifi requires python 3.6 and newer. Unfortunately, on Xenial hosts, it ships with python3.5 so this breaks.

I had to add "certifi<=2021.10.8" to my wheelhouse.txt for a charm to work on Xenial.

```
2022-06-16 03:13:37 INFO upgrade-charm Collecting certifi==2022.6.15
2022-06-16 03:13:37 INFO upgrade-charm certifi requires Python '>=3.6' but the running Python is 3.5.2
```

**Comment by ajkavanagh** [comment]
Python 3.5 is EOL (See [my message on the Juju discourse](https://discourse.charmhub.io/t/removing-py27-p35-from-charm-helpers-library/5335/7?u=ajkavanagh)) and therefore breakage like this is unfortunately to be expected.  It just means that certifi needs to be pinned in `requirements.txt`.

We probably should remove remove the py3.5 metadata from `setup.cfg` and release 1.2 to indicate that it is py36 only, although py36 is *also* EOL.  So that means py37 onwards only See [Python endoflife site](https://endoflife.date/python).

**Comment by hloeung** [comment]
Unfortunately, we still have systems running Xenial which is not yet EOL and that only has Python3.5. With that, Bionic only ships with Python3.6.

**Comment by ajkavanagh** [comment]
> Unfortunately, we still have systems running Xenial which is not yet EOL and that only has Python3.5. With that, Bionic only ships with Python3.6.

Then pin the dependencies you need for py3.5. charm-helpers, at some stage, on the main development branch won't support py3.5 or py3.6 in the near future.  You will need to pin < 1.2 for charm-helpers *now* to avoid future breakage.  It may be appropriate to add a pin for certifi in the requirements.txt now, but that would be removed in the future.
